---
- hosts: localhost
  
  tasks: 
  - name: install mysql
    yum: name={{item}} state=present
    with_items: 
      - mariadb-server
      - MySQL-python

  - name: start mariadb server
    service: name=mariadb state=started enabled=yes
 
 
  - name: create sample database called testdb
    mysql_db:
          name: testdb
          state: present

  - name: create a sample user and give it full privilage 
    mysql_user: 
          user: dick 
          password: "password" 
          priv: "testdb.*:ALL"

        
